name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
    
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          file: ${{ github.workspace }}/.github/workflows/build.Containerfile