name: Go Build

on: # rebuild any PRs and main branch changes
  push:
      branches:
        - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build devcontainer image and run Go build
        uses: devcontainers/ci@v0.3
        with:
          skipContainerUserIdUpdate: true
          runCmd: CGO_ENABLED=0 GOOS=linux go build -o /bin/emoji-data-generator-api