name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
        image: docker.io/library/golang:1.23
    
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Run unit tests
          run: go test ./...