name: Go Unit Tests
on: # rebuild any PRs and main branch changes
  push:
      branches:
        - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build devcontainer image and run Go tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: go test ./...